CREATE TABLE users (
  id INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  age INT(3) NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT FALSE,
  createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, age, admin) VALUES (
    'Алекс', 21, FALSE
);

